-- Read-only check of a hosted project after the migrations are applied.
-- Changes nothing. Every line of the result should say ok = true.
--   npx supabase db query --linked -f scripts/verify-hosted.sql
with
tables as (select c.oid, c.relname, c.relrowsecurity from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relkind = 'r'),
fn as (select p.oid, p.proname, p.prosecdef, p.proconfig from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public'),
app_fns(name) as (values ('record_payment'), ('waive_interest'), ('reverse_payment'), ('create_loan'), ('reschedule_due'), ('update_loan'), ('release_collateral'), ('accrue_all'), ('app_role'), ('today_ist'), ('can_see_customer'), ('can_see_loan'), ('next_customer_id'), ('document_tile_filled'), ('delete_customer')),
money_tables(name) as (values ('loans'), ('dues'), ('payments'), ('payment_allocations'), ('waivers'), ('collateral'), ('activity'), ('import_batches'))
select '01 all 10 tables exist' as check, (select count(*) from tables) = 10 as ok, (select string_agg(relname, ', ' order by relname) from tables) as detail
union all select '02 row level security is on for every table', not exists (select 1 from tables where not relrowsecurity), (select coalesce(string_agg(relname, ', '), 'none missing') from tables where not relrowsecurity)
union all select '03 anon has no privilege on any table', not exists (select 1 from tables t where has_table_privilege('anon', t.oid, 'select') or has_table_privilege('anon', t.oid, 'insert') or has_table_privilege('anon', t.oid, 'update') or has_table_privilege('anon', t.oid, 'delete')), ''
union all select '04 signed-in users cannot write money tables directly', not exists (select 1 from tables t join money_tables m on m.name = t.relname where has_table_privilege('authenticated', t.oid, 'insert') or has_table_privilege('authenticated', t.oid, 'update') or has_table_privilege('authenticated', t.oid, 'delete')), ''
union all select '05 signed-in users cannot delete anything', not exists (select 1 from tables t where has_table_privilege('authenticated', t.oid, 'delete')), ''
union all select '06 the reversal snapshot column is not readable', not has_column_privilege('authenticated', 'public.payments', 'before_state', 'select') and not has_column_privilege('authenticated', 'public.payments', 'idempotency_key', 'select'), ''
union all select '07 anon can run no function', not exists (select 1 from fn where has_function_privilege('anon', oid, 'execute')), (select coalesce(string_agg(proname, ', '), '') from fn where has_function_privilege('anon', oid, 'execute'))
union all select '08 signed-in users can run only the app functions', not exists (select 1 from fn where has_function_privilege('authenticated', oid, 'execute') and proname not in (select name from app_fns)), (select coalesce(string_agg(proname, ', '), '') from fn where has_function_privilege('authenticated', oid, 'execute') and proname not in (select name from app_fns))
union all select '09 every app function is there and runnable when signed in', (select count(distinct f.proname) from fn f join app_fns a on a.name = f.proname where has_function_privilege('authenticated', f.oid, 'execute')) = (select count(*) from app_fns), ''
union all select '10 privileged functions pin their search_path', not exists (select 1 from fn where prosecdef and not coalesce(proconfig::text, '') like '%search_path=public%'), (select coalesce(string_agg(proname, ', '), '') from fn where prosecdef and not coalesce(proconfig::text, '') like '%search_path=public%')
union all select '11 import and helpers are not reachable from the app', not exists (select 1 from fn where proname in ('import_book', 'undo_import', 'accrue_dues', 'trim_dues', 'log_activity', 'set_id_counters', 'period_interest', 'next_due_date') and has_function_privilege('authenticated', oid, 'execute')), ''
union all select '12 the documents bucket exists and is private, 5 MB, images and PDF only', exists (select 1 from storage.buckets where id = 'documents' and not public and file_size_limit = 5242880 and allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']), ''
union all select '13 storage has read / add / remove policies and no update policy', (select count(*) from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname like 'documents_%') = 3 and not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname like 'documents_%' and cmd = 'UPDATE'), ''
union all select '14 history locks are in place', (select count(*) from pg_trigger where not tgisinternal and tgname in ('payments_no_delete', 'payments_no_edit', 'activity_no_change', 'loans_no_delete', 'payment_allocations_no_change', 'waivers_no_delete', 'waivers_no_edit')) = 7, ''
union all select '15 no real data yet', (select count(*) from public.customers) = 0 and (select count(*) from public.loans) = 0 and (select count(*) from public.payments) = 0, (select count(*) from auth.users)::text || ' logins'
union all select '16 interest rule gives the tested answers', public.period_interest('percent', 3, 'reducing', 10000000, 6000000) = 180000 and public.period_interest('percent', 2.5, 'reducing', 3333300, 3333300) = 83300 and public.period_interest('fixed', 600050, 'fixed', 1, 1) = 600050, ''
union all select '17 monthly dates keep to the loan''s day', public.next_due_date('2026-02-28', 'monthly', '2026-01-31') = '2026-03-31' and public.next_due_date('2026-09-01', 'weekly', '2026-08-01') = '2026-09-08', ''
union all select '18 the clock is India time', public.today_ist() = (now() at time zone 'Asia/Kolkata')::date, public.today_ist()::text
order by 1;
